name: Release

on:
  push:
    branches: [main]
    paths: # only release if the version number changes in version.txt
      - 'src/Microsoft.Developer.Providers.DevCenter/version.txt'

jobs:
  release:
    uses: microsoft/developer-platform-providers/.github/workflows/release.yml@main
    with:
      name: DevCener
      path: src/Microsoft.Developer.Providers.DevCenter
    secrets: inherit
